### PR TITLE
fix #238

### LINKED ISSUE #238: 关于conf\ark\bootstrap.properties的格式问题
### Your question
我尝试\sofa-ark-samples\sample-springboot-ark这个例子。
我打包后得到一个可执行jar包 sofa-ark-sample-springboot-ark-0.6.0-executable-ark.jar
我发现在这个包里conf\ark\bootstrap.properties 这个entry并没有像其他目录文件一样的路径：
```
conf/
conf/ark/
conf/ark/bootstrap.properties
```

而是仅仅有一个conf\ark\bootstrap.properties:  如下：
```
META-INF/
META-INF/MANIFEST.MF
conf\ark\bootstrap.properties
com/
com/alipay/
com/alipay/sofa/
com/alipay/sofa/ark/
com/alipay/sofa/ark/common/
com/alipay/sofa/ark/common/util/
com/alipay/sofa/ark/common/util/StringUtils.class
com/alipay/sofa/ark/common/util/AssertUtils.class
```
在调试到
com.alipay.sofa.ark.loader.ExecutableArkBizJar#getConfClasspath
的时候，发现它并未发现conf目录

```
public final static String CONF_BASE_DIR                              = "conf/";
....
    @Override
    public List<URL> getConfClasspath() throws Exception {
        List<Archive> archives = getNestedArchives(new EntryFilter() {
            @Override
            public boolean matches(Entry entry) {
                return entry.getName().startsWith(CONF_BASE_DIR) && entry.isDirectory();
            }
        });
        List<URL> urls = new ArrayList<>();
        for (Archive archive : archives) {
            urls.add(archive.getUrl());
        }
        return urls;
    }
}
```

### PR DESCRIPTION
**Pull request by glmapper**
### Result:

Fixes #238 #228

### CODE REVIEW

File: sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/FileUtils.java [hunk 1]
```diff
@@ -94,4 +93,16 @@ public static void copyInputStreamToFile(final InputStream source, final File de
...
+    /**
+     *
+     * @param path
+     * @return
+     */
+    public static String getCompatiblePath(String path) {
+        if (System.getProperty("os.name").toLowerCase().indexOf("window") > -1) {
+            return path.replace("\\", "/");
+        }
+        return path;
```
Comment (straybirdzls) [inline sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/FileUtils.java]: Seems can directly use `File.seperator` ?

Comment (glmapper) [reply sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/FileUtils.java]: > Seems can directly use `File.seperator` ?

yes, but the test case cannot mock windows env, and then the test case will be get fail result.
