### PR TITLE
1. 删除前先标记文件夹已经被回收 2.即使删除失败也不会影响下次模块安装

### LINKED ISSUE #906: biz jar 目录清理原子性问题
### Describe the question or bug

org.apache.commons.io.FileUtils#cleanDirectory 递归清理 jar 目录下的所有文件 ，但是 java 进程被中断，会导致部分文件还残留。如果下次再次复用这个目录，会导致模块启动失败。

### Expected behavior

org.apache.commons.io.FileUtils#cleanDirectory 清理前，先标记该文件夹已经被删除，假如清理过程被中断，下次模块启动不会再次复用这个文件夹

### Actual behavior

清理过程被中断，下次模块启动无法感知文件夹是否已经完整

### Steps to reproduce

Steps to reproduce the problem:

### Screenshots

报 META-INFO/MANIFEST.MF 不存在

### Environment

- SOFAArk version: 2.2.3
- JVM version (e.g. `java -version`): 21
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by xymak**
### Motivation

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.
fix #906

### Modification

Describe the idea and modifications you've done.

### Result

Resolved or fixed #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

## Summary by CodeRabbit

- **New Features**
	- Enhanced cleanup operations by introducing a more efficient method for recycling temporary directories used by business modules.
	- Added new methods in the file utility class to handle checking and recycling temporary directories.
	- Introduced a new constant for temporary work directory recycle file suffix.

- **Bug Fixes**
	- Improved reliability by marking directories as recycled before deletion.

- **Tests**
	- Comprehensive tests added for checking and recycling temporary work directories.

### CODE REVIEW

File: sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java [hunk 1]
```diff
@@ -421,4 +426,55 @@ private static ArkLogger getLogger() {
...
     }
 
-}
+    /**
+     * recycle biz temp work dir
+     *
+     * @param bizTempWorkDir
+     * @return
+     */
+    public static boolean recycleBizTempWorkDir(File bizTempWorkDir) {
```
Comment (lvjing2) [inline sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java:435]: 这个方法为什么没有定义在 BizModel 里

**Comment by lvjing2** [comment]
image
证书也需要签下

**Review by lvjing2 — APPROVED** [review]
LGTM
